apiVersion: 1
datasources:
  # 1) Prometheus مستقیم
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  # 2) Uptrace Tempo (Traceها) - این یکی برای دیدن Trace داخل Grafana
  - name: Uptrace Tempo Project 1
    type: tempo
    access: proxy
    url: http://uptrace:80/api/tempo/1        # 1 = project_id
    jsonData:
      httpHeaderName1: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'Bearer user1_secret' # از seed_data.user_tokens
    editable: true

  # 3) (اختیاری) Prometheus از API Uptrace
  # - اگر می‌خوای متریک‌ها را از Uptrace بخوانی (نه از Prometheus مستقیم)
  - name: Uptrace Prometheus Project 1
    type: prometheus
    access: proxy
    url: http://uptrace:80/api/prometheus/1    # 1 = project_id
    jsonData:
      httpHeaderName1: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'Bearer user1_secret'  # توجه: Bearer، نه DSN
    editable: true
